#!/bin/zsh

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Set Default Editor
export EDITOR=nvim
export BROWSER=brave
export TERMINAL=alacritty

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"


############################
# Uncomment to install ruby versions on OSX M1
# THIS MAKES OPEN A TERMINAL SLOW export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
############################
# # To link Rubies to Homebrew's OpenSSL 1.1 (which is upgraded) add the following
# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
# # Fixes to install ruby versions with rbenv
# export RUBY_CFLAGS="-Wno-error=implicit-function-declaration"
# export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
# export LDFLAGS="-L/usr/local/opt/libffi/lib"
# export CPPFLAGS="-I/usr/local/opt/libffi/include"


############################
# Source personal configs
############################

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/colorsrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/colorsrc"
[ -f "${HOME}/.shell_local" ] && source "${HOME}/.shell_local" # use this to load ./config/shell/profile_mac and profile_linux
[ -f "${HOME}/.env.personal" ] && source "${HOME}/.env.personal"
[ -f "${HOME}/.env.work" ] && source "${HOME}/.env.work"



# Enable rbenv ruby versions
eval "$(rbenv init -)"
